<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEW3KdWY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEW3KdWY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEW3KdWY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEW3KdWY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEW3KdWY\App_KernelDevDebugContainer([
    'container.build_hash' => 'EW3KdWY',
    'container.build_id' => '6ce525d6',
    'container.build_time' => 1591785036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEW3KdWY');
