<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZEVAnvP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZEVAnvP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZEVAnvP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZEVAnvP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZEVAnvP\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZEVAnvP',
    'container.build_id' => '2661933d',
    'container.build_time' => 1591862665,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZEVAnvP');
