<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTRwbhxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTRwbhxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTRwbhxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTRwbhxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTRwbhxC\App_KernelDevDebugContainer([
    'container.build_hash' => 'TRwbhxC',
    'container.build_id' => 'cfa46c56',
    'container.build_time' => 1591863640,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTRwbhxC');
